// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"time"
)

type Brand struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Car struct {
	ID        int64     `json:"id"`
	BrandID   int64     `json:"brand_id"`
	Color     string    `json:"color"`
	Serial    string    `json:"serial"`
	Comfort   string    `json:"comfort"`
	Available bool      `json:"available"`
	CreatedAt time.Time `json:"created_at"`
}
