// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CountBrandByName(ctx context.Context, lower string) (int64, error)
	CreateBrand(ctx context.Context, name string) (Brand, error)
	CreateCar(ctx context.Context, arg CreateCarParams) (Car, error)
	DeleteBrand(ctx context.Context, id int64) error
	DeleteCar(ctx context.Context, id int64) error
	GetAllCars(ctx context.Context, arg GetAllCarsParams) ([]GetAllCarsRow, error)
	GetBrandById(ctx context.Context, id int64) (Brand, error)
	GetCarById(ctx context.Context, id int64) (GetCarByIdRow, error)
	SearchCars(ctx context.Context, arg SearchCarsParams) ([]SearchCarsRow, error)
	UpdateCar(ctx context.Context, arg UpdateCarParams) (Car, error)
}

var _ Querier = (*Queries)(nil)
